package cyy.dataobject;

public class SequenceDO {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.name
     *
     * @mbg.generated Tue Mar 30 11:26:17 CST 2021
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.current_vale
     *
     * @mbg.generated Tue Mar 30 11:26:17 CST 2021
     */
    private Integer currentVale;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column sequence_info.step
     *
     * @mbg.generated Tue Mar 30 11:26:17 CST 2021
     */
    private Integer step;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.name
     *
     * @return the value of sequence_info.name
     *
     * @mbg.generated Tue Mar 30 11:26:17 CST 2021
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.name
     *
     * @param name the value for sequence_info.name
     *
     * @mbg.generated Tue Mar 30 11:26:17 CST 2021
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.current_vale
     *
     * @return the value of sequence_info.current_vale
     *
     * @mbg.generated Tue Mar 30 11:26:17 CST 2021
     */
    public Integer getCurrentVale() {
        return currentVale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.current_vale
     *
     * @param currentVale the value for sequence_info.current_vale
     *
     * @mbg.generated Tue Mar 30 11:26:17 CST 2021
     */
    public void setCurrentVale(Integer currentVale) {
        this.currentVale = currentVale;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column sequence_info.step
     *
     * @return the value of sequence_info.step
     *
     * @mbg.generated Tue Mar 30 11:26:17 CST 2021
     */
    public Integer getStep() {
        return step;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column sequence_info.step
     *
     * @param step the value for sequence_info.step
     *
     * @mbg.generated Tue Mar 30 11:26:17 CST 2021
     */
    public void setStep(Integer step) {
        this.step = step;
    }
}